version: '3.9'

services:
  weather:
    build:
      context: .
      dockerfile: ./apps/weather/Dockerfile
      target: development
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./apps/weather/.env
    command: npm run start weather
    depends_on:
      - redis

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    restart: always
    ports:
      - "3002:3002"
    env_file:
      - ./apps/notifications/.env
    command: npm run start -- notifications

#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      target: development
#    restart: always
#    ports:
#      - "3000:3000"
#    env_file:
#      - .env
#    command: ["sh", "-c", "npx prisma generate --schema=src/prisma/schema.prisma && npx prisma migrate deploy --schema=src/prisma/schema.prisma && npm run start:dev"]
#    depends_on:
#      - postgres
#      - redis

#  postgres:
#    image: postgres:latest
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 1111
#      POSTGRES_DB: weather
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    restart: always

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
